#
# s3fs - FUSE-based file system backed by Amazon S3
#
# Copyright(C) 2007 Randy Rizun <rrizun@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      cache: apt
      before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq attr cppcheck libfuse-dev openjdk-7-jdk
        - sudo update-alternatives --set java /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java
      script:
        - ./autogen.sh
        - ./configure CPPFLAGS='-I/usr/local/opt/openssl/include' CXXFLAGS='-std=c++03'
        - make
        - make cppcheck
        - make check -C src
        - modprobe fuse
        - make check -C test
        - cat test/test-suite.log

    - os: osx
      osx_image: xcode8.3
      before_install:
        - brew update
        - brew install truncate
        - brew tap caskroom/cask
        - brew cask install osxfuse
        - if [ -f /Library/Filesystems/osxfusefs.fs/Support/load_osxfusefs ]; then sudo chmod +s /Library/Filesystems/osxfusefs.fs/Support/load_osxfusefs ; elif [ -f /Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse ]; then sudo chmod +s /Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse ; fi
        - brew install gnu-sed
        - sudo ln -s /usr/local/opt/gnu-sed/bin/gsed /usr/local/bin/sed
        - sudo ln -s /usr/local/opt/coreutils/bin/gstdbuf /usr/local/bin/stdbuf
        - brew install cppcheck
      script:
        - ./autogen.sh
        - PKG_CONFIG_PATH=/usr/local/opt/curl/lib/pkgconfig:/usr/local/opt/openssl/lib/pkgconfig ./configure CXXFLAGS='-std=c++03'
        - make
        - make cppcheck
        - make check -C src
        - if [ -f /Library/Filesystems/osxfusefs.fs/Support/load_osxfusefs ]; then /Library/Filesystems/osxfusefs.fs/Support/load_osxfusefs ; elif [ -f /Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse ]; then /Library/Filesystems/osxfuse.fs/Contents/Resources/load_osxfuse ; fi
        - make check -C test
        - cat test/test-suite.log


    - os: linux-ppc64le
      sudo: required
      dist: trusty
      cache: apt
      before_install:
        - sudo add-apt-repository -y ppa:openjdk-r/ppa 
        - sudo apt-get update -qq
        - sudo apt-get install -qq attr libfuse-dev openjdk-7-jdk
        - sudo update-alternatives --set java /usr/lib/jvm/java-7-openjdk-ppc64el/jre/bin/java
        - sudo git clone --branch 1.61 https://github.com/danmar/cppcheck.git
        - pwd
        - cd ./cppcheck
        - sudo make
        - sudo make install
        - cd ../ 
      script:
        - ./autogen.sh
        - ./configure CPPFLAGS='-I/usr/local/opt/openssl/include' CXXFLAGS='-std=c++03'
        - make
        - make cppcheck
        - make check -C src
        - modprobe fuse
        - make check -C test
        - cat test/test-suite.log

#
# Local variables:
# tab-width: 4
# c-basic-offset: 4
# End:
# vim600: noet sw=4 ts=4 fdm=marker
# vim<600: noet sw=4 ts=4
#
